# This is a generated file. Not intended for manual editing.
services:
  bookmakerbackend.api:
    build:
      context: "C:\\Users\\k_dod\\repos\\BookmakerBackend"
      dockerfile: "src/BookmakerBackend.Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/BookmakerBackend.Api.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "bookmakerbackend.api:dev"
    ports: []
    volumes:
    - "C:\\Users\\k_dod\\repos\\BookmakerBackend\\src\\BookmakerBackend.Api:/app:rw"
    - "C:\\Users\\k_dod\\repos\\BookmakerBackend:/src:rw"
    - "C:\\Users\\k_dod\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
